version: '3.6'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgUser
      POSTGRES_PASSWORD: pgPassword
      POSTGRES_DB: database

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_USER: ${POSTGRES_USER:-pgUser}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-pgPassword}
      ADMINER_DEFAULT_TYPE: postgresql
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: ${POSTGRES_DB:-database}